version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: bash -c "make && ./bin/server 8033 && tail -f /dev/null"
    ports:
      - '8033:8033'




