version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspaces:cached
      - ~/.ssh:/root/.ssh:cached
      - ~/.vscode-server:/root/.vscode-server:cached

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined